name: Gitleaks Scan

on:
  workflow_call:

jobs:

  gitleaks: 
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Install prerequisites
      run: |
        set -euo pipefail
        sudo apt-get update -qq
        sudo apt-get install -y -qq git curl unzip ca-certificates

    - name: Set up gitleaks
      run: |
        set -euo pipefail
        GITLEAKS_VERSION=$(curl -s "https://api.github.com/repos/gitleaks/gitleaks/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
        wget -qO gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
        tar -xzf gitleaks.tar.gz -C /usr/local/bin gitleaks
        echo "gitleaks version:"
        gitleaks version

    - name: Run gitleaks
      run: |
        set -euo pipefail
        echo "Running Gitleaks"
        gitleaks detect --source ${{github.workspace}} --report-format json --report-path gitleaks-report.json
        echo "Gitleaks scan completed. Report saved as gitleaks-report.json"

    - name: Upload gitleaks report
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks-report.json
