name: Helm Lint

on:
  workflow_call:
    inputs:
      app:
        description: "Name of the app"
        required: true
        type: string
      helm_version:
        description: "Version of helm to install"
        required: true
        type: string

jobs:

  helm-lint:
    name: Helm Lint 
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout repository
      working-directory: ${{ github.workspace }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        git init -q
        git remote add origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git fetch --depth=1 origin "$GITHUB_SHA"
        git checkout -q FETCH_HEAD

    - name: Install Helm
      env:
        HELM_VERSION: ${{ inputs.helm_version }}
      run: |
        set -euo pipefail
        curl -fsSLO "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz"
        curl -fsSLO "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256sum"
        sha256sum --check "helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256sum"
        tar -zxf "helm-${HELM_VERSION}-linux-amd64.tar.gz"
        sudo mv linux-amd64/helm /usr/local/bin/helm
        echo "helm version: $(helm version)"

    - name: Lint Helm Chart
      run: |
        set -euo pipefail
        helm lint ./helm-apps/${{ inputs.app }}
      continue-on-error: false

    - name: Check template
      run: |
        set -euo pipefail
        helm template ./helm-apps/${{ inputs.app }} --debug
      continue-on-error: false