name: Helm Lint

on:
  workflow_call:
    inputs:
      app:
        description: "Name of the app"
        required: true
        type: string
      helm_version:
        description: "Version of helm to install"
        required: true
        type: string

jobs:

  ecr-push:
    name: ECR 
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v7

    - name: Install Helm
      env:
        HELM_VERSION: ${{ inputs.helm_version }}
      run: |
        set -euo pipefail
        curl -fsSLO "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz"
        curl -fsSLO "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256sum"
        sha256sum --check "helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256sum"
        tar -zxf "helm-${HELM_VERSION}-linux-amd64.tar.gz"
        sudo mv linux-amd64/helm /usr/local/bin/helm
        echo "helm version: $(helm version)"

    - name: Lint Helm Chart
      run: |
        set -euo pipefail
        helm lint ./helm-apps/${{ inputs.app }}
      continue-on-error: false

    - name: Check template
      run: |
        set -euo pipefail
        helm template ./helm-apps/${{ inputs.app }} --debug
      continue-on-error: false