name: 'Terraform Lint'

on:
  workflow_call:
    inputs:
      working_directory:
        description: "Path of the working directory"
        required: true
        type: string
      tf_version:
        description: "Version of terraform to install"
        required: true
        type: string

jobs:

  checkout:
    uses: ./.github/workflows/checkout.yaml

  terraform:
    runs-on: ubuntu-latest
    needs: checkout
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
    - name: Download source artifact
      uses: actions/download-artifact@v4
      with:
        name: checkout-source
        path: ${{ github.workspace }}/checkout-source

    - name: Set up tfenv
      run: |
        git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
        ln -s ~/.tfenv/bin/* /usr/local/bin
        mkdir -p ~/.local/bin/
        . ~/.profile
        ln -s ~/.tfenv/bin/* ~/.local/bin
        echo "tvenf location $(which tfenv)"
        echo "tfenv version $(tfenv --version)"

    - name: Set up terraform
      run: |
        tfenv install ${{ inputs.tf_version }}
        tfenv use ${{ inputs.tf_version }}

    - name: Check terraform version
      run: echo "Terraform version $(terraform version)"

    - name: Terraform fmt check
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Run 'terraform init' (no backend)
      run: terraform init -backend=false -input=false

    - name: Run 'terraform validate'
      run: terraform validate